- name: disable firewalld
  service: name=firewalld state=stopped enabled=no
  ignore_errors: True  #when firewalld is stopped

- name: Create collectd container
  docker_container:
    name: collectd
    image: andreasjansson/collectd-write-graphite:latest
    restart_policy: always
    env:
      HOST_NAME: "{{ ansible_hostname }}"
      GRAPHITE_HOST: "{{ graphite_host }}"
      GRAPHITE_PREFIX: "collectd_"
      COLLECT_INTERVAL: "120"
    volumes:
      - /data:/hostfs:ro
