- hosts: all
  roles:
    - { role: java, when: accept_oracle_licence }

- hosts: zk
  roles:
    - zookeeper

- hosts: kafka
  roles:
    - kafka

- hosts: kafka_manager
  roles:
    - kafka_manager

- hosts: docker
  roles:
    - docker
