- hosts: zk
  roles:
    - java
    - zookeeper
  serial: 1

- hosts: kafka
  gather_facts: yes
  roles:
    - java
    - kafka
  serial: 1

- hosts: monitoring
  roles:
    - docker
    - graphite
    - grafana
    - java

- hosts: collectd
  gather_facts: yes
  roles:
    - docker
    - collectd
