kafka:
  version: 0.9.0.1
  scala_version: 2.11
  mirror: http://mirrors.ukfast.co.uk/sites/ftp.apache.org
  data_dir: /var/lib/kafka
  install_dir: "/etc"
# This does not have to be every Zookeeper host, but the more the better
#  by default, we assume this is run at the same time as Zookeeper provisioning
zk_hosts: "{{ groups['zk'] }}" # This does not have to be every Zookeeper host
zk_client_port: 2181 # TODO Check if this should be a string
kafka_cluster_info:
  kafka-node-1: # TODO replace with real hostnames
    broker_id: 1
  kafka-node-2:
    broker_id: 2
  kafka-node-3:
    broker_id: 3
# Should be a list of node hostnames to node info
# Example:
# kafka_cluster_info:
#   kafka-node-1:
#     broker_id: 1
#   kafka-node-2:
#     broker_id: 2
#   kafka-node-3:
#     broker_id: 3
