kafka:
  version: 2.0.0
  scala_version: 2.11
  mirror: http://mirrors.ukfast.co.uk/sites/ftp.apache.org
  data_dir: /data/kafka
  install_dir: "/etc"
# This does not have to be every Zookeeper host, but the more the better
#  by default, we assume this is run at the same time as Zookeeper provisioning
zk_hosts: "{{ groups['zk'] }}" # This does not have to be every Zookeeper host
zk_client_port: "{{ zk_client_port }}"
kafka_cluster_info: "{{ kafka_cluster_info }}"
