- name: install the latest version of Apache
  yum:
    name: java-1.8.0-openjdk
    state: latest

- name: /etc/profile.d/java8.sh
  template: >
    src=profile.java8.sh.j2
    dest=/etc/profile.d/{{  symlink_to  }}.sh
    owner=root group=root mode=0644
