- name: install the latest version of Apache
  yum:
    name: {{ openjdk_package }}
    state: latest

- name: /etc/profile.d/java8.sh
  template: >
    src=profile.java8.sh.j2
    dest=/etc/profile.d/openjdk_java8.sh
    owner=root group=root mode=0644
