- name: disable firewalld
  service: name=firewalld state=stopped enabled=no
  ignore_errors: True  #when firewalld is stopped

- name: create group
  group:
    name: graphite
    state: present

- name: create user
  user:
    name: graphite
    group: graphite

- name: create graphite directory
  file: path=/data/graphite state=directory owner=graphite group=graphite mode=0755

- name: create graphite storage directory
  file: path=/data/graphite/storage state=directory owner=graphite group=graphite mode=0755

- name: create graphite configuration directory
  file: path=/data/graphite/conf state=directory owner=graphite group=graphite mode=0755

- name: Copy config file to remote machine
  copy:
    src: storage-aggregation.conf
    dest: /data/graphite/conf/storage-aggregation.conf
    owner: graphite
    group: graphite
    
- name: Copy config file to remote machine
  copy:
    src: storage-schemas.conf
    dest: /data/graphite/conf/storage-schemas.conf
    owner: graphite
    group: graphite

- name: Create a Graphite container
  docker_container:
    name: graphite
    image: graphiteapp/graphite-statsd:1.0.2-1
    ports:
      - "80:80"
      - "2003:2003"
      - "2004:2004"
      - "2023:2023"
      - "2024:2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - /data/graphite/conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
      - /data/graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
      - /data/graphite/storage:/opt/graphite/storage
