- name: disable firewalld
  service: name=firewalld state=stopped enabled=no
  ignore_errors: True  #when firewalld is stopped

- name: create group
  group:
    name: influx
    state: present

- name: create user
  user:
    name: influx
    group: influx

- name: create influx directory
  file: path=/data/influx state=directory owner=influx group=influx mode=0755

- name: create influx storage directory
  file: path=/data/influx/storage state=directory owner=influx group=influx mode=0755

- name: create influx configuration directory
  file: path=/data/influx/conf state=directory owner=influx group=influx mode=0755

- name: Copy config file to remote machine
  copy:
    src: influxdb.conf
    dest: /data/influx/conf/influxdb.conf
    owner: influx
    group: influx
    
- name: Create an InfluxDB container
  docker_container:
    name: influxdb
    image: influxdb/influxdb:1.3.7
    restart_policy: always
    ports:
      - "8086:8086"
      - "2003:2003"
    volumes:
      - /data/influx/conf/influxdb.conf:/etc/influxdb/influxdb.conf
      - /data/influx/storage:/var/lib/influxdb

- name: Create database
  influxdb_database:
      hostname: "{{influxdb_ip_address}}"
      database_name: "{{influxdb_database_name}}"
      state: present

- name: Create 1 week retention policy
  influxdb_retention_policy:
      hostname: "{{influxdb_ip_address}}"
      database_name: "{{influxdb_database_name}}"
      policy_name: one_week
      duration: {{ retention_duration }}
      replication: 1
