- name: disable firewalld
  service: name=firewalld state=stopped enabled=no
  ignore_errors: True  #when firewalld is stopped
  tags: kafka-manager

- name: create group
  group:
    name: kafka-manager
    state: present
  tags: kafka-manager

- name: create user
  user:
    name: kafka-manager
    group: kafka-manager
  tags: kafka-manager

- name: Setting internal variable
  set_fact:
    kafka_manager_name: kafka-manager-{{ kafka_manager.version }}
  tags: kafka-manager

- name: Setting internal variable
  set_fact:
    kafka_manager_dir: "{{ kafka_manager.install_dir }}/{{ kafka_manager_name }}"
  tags: kafka-manager

- name: Extract Kafka-Manager
  unarchive:
    src: "{{ kafka_manager_name }}.zip"
    dest: "{{ kafka_manager.install_dir }}"

# Config and start Kafka-Manager
- name: systemd start script
  template:
    src: kafka-manager-systemd.j2
    dest: /etc/systemd/system/kafka-manager.service
    owner: kafka-manager
    group: kafka-manager
    mode: 644
  notify: start kafka-manager
  tags: kafka-manager
