
- name: disable firewalld
  service: name=firewalld state=stopped enabled=no
  ignore_errors: True  #when firewalld is stopped

- name: create group
  group:
    name: akhq
    state: present

- name: create user
  user:
    name: akhq
    group: akhq

- name: create akhq directory
  file: path=/data/akhq state=directory owner=akhq group=akhq mode=0755

- name: create akhq configuration directory
  file: path=/data/akhq/conf state=directory owner=akhq group=akhq mode=0755

- name: Copy config file to remote machine
  copy:
    src: storage-aggregation.conf
    dest: /data/akhq/conf/application.yml
    owner: akhq
    group: akhq
    
- name: Create an akhq container
  docker_container:
    name: akhq
    image: tchiotludo/akhq:0.15.0
    restart_policy: always
    ports:
      - "8080:8080"
    volumes:
      - /data/akhq/conf/application.yml:/app/application.yml

