- include_vars: hostname_vars.yml
  when: vagrant_kafka_cluster_info is not defined

- name: Setting internal variable
  set_fact:
    rest_proxy_name: kafka-rest-{{ rest_proxy.version }}
  tags: rest_proxy

- name: REST Proxy | Setting internal variable
  set_fact:
    rest_proxy_dir: "{{ rest_proxy.install_dir }}/{{ rest_proxy_name }}"
  tags: rest_proxy

- name: check if tar has been downloaded
  command: test -f /tmp/{{ rest_proxy_name }}.tar.gz
  register: rest_proxy_tar_downloaded
  failed_when: rest_proxy_tar_downloaded.rc not in [0, 1]
  changed_when: False
  tags: rest_proxy

- name: Ensure REST proxy tar is downloaded
  get_url:
    url: "{{ rest_proxy.mirror }}/v{{ rest_proxy.version }}.tar.gz"
    dest: /tmp
  tags: rest_proxy
  when: rest_proxy_tar_downloaded.rc == 1

- name: Ensure tar is extracted
  command: tar xzf /tmp/v{{ rest_proxy.version }}.tar.gz chdir="{{ rest_proxy.install_dir }}"
  tags: rest_proxy

# Config and start REST Proxy
- name: Ensure config file is present
  template:
    src: kafka-rest-properties
    dest: "{{ rest_proxy_dir }}/config/kafka-rest-properties"
  notify: restart rest_proxy
  tags: rest_proxy

- name: systemd start script
  template:
    src: rest_proxy-systemd.j2
    dest: /etc/systemd/system/rest_proxy.service
    owner: root
    group: root
    mode: 644
  notify: start rest_proxy
  tags: rest_proxy
